# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3d887c45534391c9c4be4d71cf99622a"
name = "sample-app"
handle = "sample-app-1717"
application_url = "https://trinity-interfaces-tuner-snowboard.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-2d9f9556.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://trinity-interfaces-tuner-snowboard.trycloudflare.com/auth/callback",
  "https://trinity-interfaces-tuner-snowboard.trycloudflare.com/auth/shopify/callback",
  "https://trinity-interfaces-tuner-snowboard.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
